### ISSUE TITLE
在很多手机上运行都不会报错，但是在台电平板上面运行会报错的方法。

### ISSUE THREAD

**Issue by 395193253** [hongyangAndroid/okhttputils#278]
多文件和map共传时，会报一空。现在目前只发现台电平板上面会报这个错误。

错误信息如下：

 Process: com.cga.cgaapplication, PID: 17137
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
                                                                            at okhttp3.RequestBody.create(RequestBody.java:55)
                                                                            at com.zhy.http.okhttp.request.PostFormRequest.addParams(PostFormRequest.java:113)
                                                                            at com.zhy.http.okhttp.request.PostFormRequest.buildRequestBody(PostFormRequest.java:47)
                                                                            at com.zhy.http.okhttp.request.OkHttpRequest.generateRequest(OkHttpRequest.java:70)
                                                                            at com.zhy.http.okhttp.request.RequestCall.generateRequest(RequestCall.java:79)
                                                                            at com.zhy.http.okhttp.request.RequestCall.buildCall(RequestCall.java:55)
                                                                            at com.zhy.http.okhttp.request.RequestCall.execute(RequestCall.java:84)
                                                                            at com.cga.cgaapplication.user.register.GRRZFragment.senRegisterInfo(GRRZFragment.java:375)
                                                                            at com.cga.cgaapplication.user.register.GRRZFragment.onClick(GRRZFragment.java:212)
                                                                            at android.view.View.performClick(View.java:4756)
                                                                            at android.view.View$PerformClick.run(View.java:19749)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

报错信息指向： .execute(new OkManagerCallback() {      这句

**Comment by ccclll1990** [comment]
同问这个错误,有解吗?
