### ISSUE TITLE
建议对传递的String类型的URL用HttpUrl进行处理，得到的对象为空直接onError

### ISSUE THREAD

**Issue by marchfly** [hongyangAndroid/okhttputils#285]
okhttp对传递的URL用HttpUrl类处理过，如果为空直接抛了一个没有捕获的异常。应用就会crash这样感觉很不好，为什么不自己处理让这个异常经过onError呢

**Comment by GitSmark** [comment]
java.lang.IllegalArgumentException: unexpected url: xxxxx
at okhttp3.Request$Builder.url(Unknown Source)
at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(Unknown Source)
at com.zhy.http.okhttp.request.OkHttpRequest.<init>(Unknown Source)
at com.zhy.http.okhttp.request.PostFormRequest.<init>(Unknown Source)
at com.zhy.http.okhttp.builder.PostFormBuilder.build(Unknown Source)
URL异常直接crash.
