### ISSUE TITLE
https双向验证出错

### ISSUE THREAD

**Issue by yiyi99** [hongyangAndroid/okhttputils#323]
出错信息：
E/OkHttp: ========request'log=======end
W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:33)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
W/System.err: 	Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
W/System.err: 		... 29 more
W/System.err: 	Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7ffeec46d000: Failure in SSL library, usually a protocol error
W/System.err: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE (external/boringssl/src/ssl/s3_pkt.c:610 0x7ffeec41bc00:0x00000001)
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
W/System.err: 		... 28 more
W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7ffeec46d000: Failure in SSL library, usually a protocol error
W/System.err: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE (external/boringssl/src/ssl/s3_pkt.c:610 0x7ffeec41bde0:0x00000001)
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
W/System.err: 	... 28 more

代码如下：
InputStream [] arris = new InputStream[1];
            arris[0] = new ByteArrayInputStream(MyCert_Server.getBytes());

            HttpsUtils.SSLParams sslParams = HttpsUtils.getSslSocketFactory(arris, getApplicationContext().getAssets().open("client.bks"), "test1");

            OkHttpClient okHttpClient = new OkHttpClient.Builder()
                    .connectTimeout(10000L, TimeUnit.MILLISECONDS)
                    .readTimeout(10000L, TimeUnit.MILLISECONDS)
                    .addInterceptor(new LoggerInterceptor("OkHttp"))
                    .sslSocketFactory(sslParams.sSLSocketFactory, sslParams.trustManager)
                    .build();
            OkHttpUtils.initClient(okHttpClient);

String url = "";
        url="https://192.168.1.99:8443/test1";
        mTv.setText("");
        OkHttpUtils
                .get()
                .url(url)
                .id(100)
                .build()
                .execute(new MyStringCallback());
使用ie浏览器测试双向验证通过。

**Comment by yiyi99** [comment]
是不是Android7的sdk改了啊？我用Android5是可以的。
