### ISSUE TITLE
开机第一次请求网络，使用的这个框架报错了

### ISSUE THREAD

**Issue by huanyuan** [hongyangAndroid/okhttputils#353]
11-30 01:11:00.857  5596  7526 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
11-30 01:11:00.857  5596  7526 E AndroidRuntime: Process: com.cyx.amazinglauncher, PID: 5596
11-30 01:11:00.857  5596  7526 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at com.zhy.http.okhttp.cookie.store.MemoryCookieStore.add(MemoryCookieStore.java:26)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at com.zhy.http.okhttp.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:29)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:918)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:648)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.RealCall.getResponse(RealCall.java:244)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.RealCall.access$100(RealCall.java:30)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-30 01:11:00.857  5596  7526 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
11-30 01:11:00.857  4131  4131 D AlarmManagerService: Kernel timezone updated to 0 minutes west of GMT

**Comment by huanyuan** [comment]
开机第一次请求网络，使用的这个框架报错了
