### ISSUE TITLE
使用okhttputils的时候在酷派大神F2上出现闪退现象

### ISSUE THREAD

**Issue by tx123456** [hongyangAndroid/okhttputils#397]
这里提示在Application中初始化失败，没有找到OkHttpClient这个类，这个问题目前只在酷派大神F2这个机型中出现，其他手机目前还没有发现这个问题，

然后我去百度了下，说是没有依赖okio这个库，关键是我已经依赖了okio

这是我的初始化方法
 OkHttpClient okHttpClient = new OkHttpClient.Builder().addInterceptor(new LoggerInterceptor("OkHttpRequest")).connectTimeout(10000L,TimeUnit.MILLISECONDS).readTimeout(
10000L, TimeUnit.MILLISECONDS) .followSslRedirects(false).followRedirects(false).build();
 OkHttpUtils.initClient(okHttpClient);

下面是错误日志

W/dalvikvm: VFY: unable to find class referenced in signature (Lokio/BufferedSource;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokio/BufferedSource;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokio/BufferedSource;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokio/BufferedSource;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lokio/BufferedSource;)
W/dalvikvm: VFY: unable to resolve interface method 64022: Lokio/BufferedSource;.readString (Ljava/nioarset/Charset;)Ljava/lang/String;
W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lokhttp3/internal/Util;
W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lokhttp3/OkHttpClient;
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4185be00)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.tanxin.aiguiquan, PID: 15837
                  java.lang.NoClassDefFoundError: okio.Buffer
                      at okhttp3.ResponseBody.create(ResponseBody.java:208)
                      at okhttp3.internal.Util.<clinit>(Util.java:48)
                      at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:122)
                      at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:453)
                      at com.example.tanxin.aiguiquan.ui.MyAppcation.onCreate(MyAppcation.java:38)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1008)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4508)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:142)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1273)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5217)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                      at dalvik.system.NativeStart.main(Native Method)

希望有大佬能解决这个问题，感激不尽

**Comment by tx123456** [comment]
已解决，这是方法超过64k造成的
